package com.example.deploy.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import org.springframework.boot.autoconfigure.domain.EntityScan;

@DynamoDBTable(tableName = "Dynamo")
@Data
public class Dynamo {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String category;
    @DynamoDBAttribute
    private String productName;


    public String getId() {
        return id;
    }


    public String getCategory() {
        return category;
    }

    public String getProductName() {
        return productName;
    }

}
